# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
b = np.array([0,0,0,0,0,0,0,0,0,0])
b

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [3]:
np.size(b)

10

3. Create a vector with values ranging from 10 to 49

In [4]:
c = np.arange(10,50)
c

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [5]:
np.shape(c)

(40,)

5. Print the type of the previous array in question 3

In [6]:
print(type(c))

<class 'numpy.ndarray'>


6. Print the numpy version and the configuration


In [7]:
print(np.version)
print(np.show_config)

<module 'numpy.version' from 'D:\\ja\\lib\\site-packages\\numpy\\version.py'>
<function show at 0x0000000005523B88>


7. Print the dimension of the array in question 3


In [8]:
np.ndim(c)

1

8. Create a boolean array with all the True values

In [9]:
d = np.array([1,2,3,4])
d

array([1, 2, 3, 4])

In [10]:
d>0

array([ True,  True,  True,  True])

9. Create a two dimensional array




In [11]:
e = np.array([[1,2,3,4,5],[6,7,8,9,10]])
e

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [12]:
e.ndim

2

10. Create a three dimensional array



In [13]:
f = np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
f

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]]])

In [14]:
f.ndim

3

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [15]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
a=np.arange(10,0,-1)
a

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [17]:
a = np.array([0,0,0,0,0,0,0,0,0,0])
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [18]:
np.size(a)

10

In [20]:
a[5]=1
a

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0])

13. Create a 3x3 identity matrix

In [21]:
a = np.array([[[1,1,1],[1,1,1],[1,1,1]]])
a

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [22]:
arr = np.array([1,2,3,4,5])
float_number = arr.astype(np.float64)
float_number

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [24]:
arr1 = np.array([[1.,2.,3.],[4.,5.,6.]])
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
arr3=arr1*arr2
arr3

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [25]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[0,4,1],[7,2,12]])

In [26]:
arr1>arr2

array([[ True, False,  True],
       [False,  True, False]])

In [27]:
arr1>arr2

array([[ True, False,  True],
       [False,  True, False]])

17. Extract all odd numbers from arr with values(0-9)

In [28]:
a = np.arange(1,10,2)
a

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [31]:
np.where(a>=0,-1,1)

array([-1, -1, -1, -1, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [32]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
arr[5:9]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [37]:
arr2d=np.ones((5,5))
arr2d=arr2d.astype(np.int32)
arr2d

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [38]:
arr2d[1:-1,1:-1]=0
arr2d

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [39]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[0:3]=[[5,6,7],[8,9,10],[11,12,13]]
arr2d

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [40]:
arr3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [41]:
arr3d[0]=64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [42]:
arr=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [43]:
arr[0:1]

array([[0, 1, 2, 3, 4]])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [44]:
ar2d=np.array([[0,1,2,3,4],[5,6,7,8,9]])
ar2d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [45]:
ar2d[1:2]

array([[5, 6, 7, 8, 9]])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [46]:
a2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
a2d[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [48]:
array=np.random.randn(10,10)
array

array([[-0.86764721,  0.21052687, -0.2432706 , -0.66993811,  2.07925816,
        -1.49765609, -1.77685765, -0.05817822, -0.59437297,  0.43977622],
       [-0.36942291, -1.61010377,  0.12180109, -0.64815483,  0.49498175,
         0.58268878, -1.44534381, -0.7024734 , -0.47579483,  1.05474558],
       [-0.50882334,  1.4283766 ,  0.23603098,  1.47302093, -0.01348277,
         0.86221481, -0.987385  , -0.00332663,  0.36893206, -0.62480824],
       [-0.02227081,  1.22418283, -1.13843601,  1.11344304,  0.18950959,
        -0.21653754,  0.32148142, -0.49936943, -0.9949582 , -0.62801036],
       [-0.33318123,  1.30456208, -1.01281194,  0.8684727 , -0.82156034,
         0.04100078,  1.35428604,  0.59416055,  1.00761778, -0.03687631],
       [-0.69082652, -0.27986427, -0.05460591, -0.95476657,  1.67662804,
        -0.76024891, -0.08317142,  0.61007327,  0.51027278, -0.80015583],
       [-1.01567115, -1.72619179,  1.07764856, -0.14027056, -0.1739356 ,
         2.38836694, -0.02224616,  0.2340264 

In [49]:
np.max(array)

2.3883669404048677

In [50]:
np.min(array)

-1.8180096279985007

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [51]:
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])

In [52]:
np.unique(a)

array([1, 2, 3, 4, 5, 6])

In [53]:
np.unique(b)

array([ 2,  4,  7,  8,  9, 10])

In [54]:
np.unique((a,b))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [55]:
a=np.array([1,2,3,2,3,4,3,4,5,6])
b=np.array([7,2,10,2,7,4,9,4,9,8])

In [56]:
print(np.where(np.intersect1d(a,b)))

(array([0, 1], dtype=int64),)


29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [59]:
names=np.array(["bob","joe","will","bob","will","joe","joe"])
names

array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'], dtype='<U4')

In [66]:
data=np.random.randn(7,4)
data=names[names!="will"]
data

array(['bob', 'joe', 'bob', 'joe', 'joe'], dtype='<U4')

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [72]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [76]:
data=np.random.randn(7,4)
data=names[(names!='Will')&(names!='Joe')]
data

array(['Bob', 'Bob'], dtype='<U4')

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [80]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]])
print(arr)
np.ndim(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]


2

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [81]:
arr2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
arr2d.reshape(2,2,4)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [84]:
np.hstack(arr2d)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [86]:
np.vstack(arr2d)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [87]:
array = np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
np.sqrt(array)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [89]:
arr1d=np.random.randn(12)
arr1d

array([-0.3539858 , -0.8010491 , -1.52024859, -0.87357878,  1.04294715,
        0.05850022,  0.09112232,  0.33359083, -0.2825651 , -0.01556718,
       -0.73886894, -0.56776992])

In [90]:
arr2d=np.random.randn(12)
arr2d

array([ 0.58921185,  0.07480304,  0.23305385,  1.89749452,  1.47841527,
       -0.70866039,  0.98828313, -1.45264856,  0.56528199, -0.52767488,
       -1.94838758,  0.79480828])

In [91]:
np.max((arr1d,arr2d))

1.8974945209039484

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [92]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [93]:
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [94]:
np.sort(names)

array(['Bob', 'Bob', 'Joe', 'Joe', 'Joe', 'Will', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [95]:
a=np.array([1,2,3,4,5])
b=np.array([5,6,7,8,9])

In [96]:
np.delete(b,0)

array([6, 7, 8, 9])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [97]:
sampleArray= np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray

array([[34, 43, 73],
       [82, 22, 12],
       [53, 94, 66]])

In [98]:
np.delete(sampleArray,2,axis=1)

array([[34, 43],
       [82, 22],
       [53, 94]])

In [99]:
np.insert(sampleArray,2,[10,10,10],axis=1)

array([[34, 43, 10, 73],
       [82, 22, 10, 12],
       [53, 94, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [100]:
x=np.array([[1.,2.,3.],[4.,5.,6.]])
y=np.array([[6.,23.],[-1,7.],[8,9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [102]:
arr=np.random.rand(20)
arr

array([0.84858962, 0.00401588, 0.36735734, 0.65543653, 0.5514731 ,
       0.79322251, 0.83222123, 0.13889617, 0.87457632, 0.80262768,
       0.22647336, 0.74015494, 0.82868227, 0.76614431, 0.40782518,
       0.00595496, 0.50977595, 0.0367659 , 0.57658218, 0.32821885])

In [103]:
np.cumsum(arr)

array([ 0.84858962,  0.8526055 ,  1.21996284,  1.87539937,  2.42687247,
        3.22009498,  4.05231621,  4.19121237,  5.06578869,  5.86841638,
        6.09488973,  6.83504468,  7.66372695,  8.42987126,  8.83769644,
        8.8436514 ,  9.35342736,  9.39019326,  9.96677543, 10.29499428])