# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [2]:
import numpy as np
arr=np.array([0,1,2,3,4,5,6,7,8,9])
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr.reshape(2,1,5)

array([[[0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [4]:
arr1=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2=np.array([[1,1,1,1,1],[1,1,1,1,1]])

In [5]:
print(arr1)
print(arr2)
np.vstack((arr1,arr2))

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [18]:
arr1=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr2=np.array([[1,1,1,1,1],[1,1,1,1,1]])
print(arr1)
print(arr2)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]


In [19]:
np.hstack((arr1,arr2))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [20]:
arr=np.array([[0,1,2,3,4],[5,6,7,8,9]])
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [23]:
np.ravel(arr)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
arr.flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [14]:
arr=np.array([[[0,1,2,3,4],[5,6,7,8,9],[10,11,12,13,14]]])
arr

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [15]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [16]:
arr=np.array([0,1,2,3,4,5,6,7,8,9,10,11,12,13,14])
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
arr.reshape(5,1,3)

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]],

       [[12, 13, 14]]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [26]:
arr=5*np.ones([5,5])
arr=arr.astype(np.int32)
arr

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [27]:
np.sqrt(arr)

array([[2.23606798, 2.23606798, 2.23606798, 2.23606798, 2.23606798],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798, 2.23606798],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798, 2.23606798],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798, 2.23606798],
       [2.23606798, 2.23606798, 2.23606798, 2.23606798, 2.23606798]])

## Question:8

### Create 5x6 an array and find the mean?

In [30]:
arr=10*np.ones([5,6])

In [31]:
arr=arr.astype(np.int32)

In [32]:
arr

array([[10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10]])

In [33]:
np.mean(arr)

10.0

## Question:9

### Find the standard deviation of the previous array in Q8?

In [34]:
np.std(arr)

0.0

## Question:10

### Find the median of the previous array in Q8?

In [35]:
np.median(arr)

10.0

## Question:11

### Find the transpose of the previous array in Q8?

In [36]:
np.transpose(arr)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [40]:
arr = 10*np.ones([4,4])

In [41]:
arr=arr.astype(np.int32)

In [42]:
arr

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [43]:
np.diag(arr)

array([10, 10, 10, 10])

## Question:13

### Find the determinant of the previous array in Q12?

In [44]:
arr=10*np.ones([4,4])
arr=arr.astype(np.int32)
arr

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [45]:
np.linalg.det(arr)

0.0

## Question:14

### Find the 5th and 95th percentile of an array?

In [46]:
arr=np.array([1,2,3,4,5,6,7,8,9,10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
print(np.percentile(arr,5))
print(np.percentile(arr,95))

1.4500000000000002
9.549999999999999


## Question:15

### How to find if a given array has any null values?

In [52]:
arr = np.array([1,2,3,4,5,np.NAN])
arr

array([ 1.,  2.,  3.,  4.,  5., nan])

In [53]:
np.isnan(arr)

array([False, False, False, False, False,  True])